
//типы выбранного тнгртдтента
export const SELECT_INGREDIENT: 'SELECT_INGREDIENT' = 'SELECT_INGREDIENT';
export const DELETE_SELECTED_INGREDIENT: 'DELETE_SELECTED_INGREDIENT_DATA' = 'DELETE_SELECTED_INGREDIENT_DATA';

//тип страницы ингредиента
export const INGREDIENT_WINDOW_OPEN: 'INGREDIENT_WINDOW' = 'INGREDIENT_WINDOW';
export const INGREDIENT_WINDOW_CLOSE: 'INGREDIENT_WINDOW_CLOSE' = 'INGREDIENT_WINDOW_CLOSE';
