export const BURGER_INGREDIENT: 'BURGER_INGREDIENT' = 'BURGER_INGREDIENT';
export const CLEAR_INGREDIENT_ORDER: 'CLEAR_INGREDIENT_ORDER' = 'CLEAR_INGREDIENT_ORDER';
export const DELETE_BURGER_INGREDIENT: 'DELETE_BURGER_INGREDIENT' = 'DELETE_BURGER_INGREDIENT';
export const MOVE_CONSTRUCTOR_INGREDIENTS: 'MOVE_CONSTRUCTOR_INGREDIENTS' = 'MOVE_CONSTRUCTOR_INGREDIENTS';