//типы выбранного заказа
export const SELECT_ORDER: 'SELECT_ORDER' = 'SELECT_ORDER';
export const DELETE_SELECTED_ORDER_DATA: 'DELETE_SELECTED_ORDER_DATA' = 'DELETE_SELECTED_ORDER_DATA';

//типы страницы заказа 
export const ORDER_WINDOW_OPEN: 'ORDER_WINDOW_OPEN' = 'ORDER_WINDOW_OPEN';
export const ORDER_WINDOW_CLOSE: 'ORDER_WINDOW_CLOSE' = 'ORDER_WINDOW_CLOSE';
